// lib/patients.ts — All Supabase calls for the Patients feature live here
// This is the SINGLE SOURCE OF TRUTH for patient data (no more dummy arrays, no FastAPI for this).

import { supabase } from "@/lib/supabase"

// ── Type matching your exact Supabase "patients" table columns ──────────
export type Patient = {
  id: string            // uuid, auto-generated by Supabase
  name: string
  age: number
  gender: string
  bloodGroup: string | null
  phone: string | null
  email: string | null
  address: string | null
  condition: string
  status: string
  doctor: string | null
  bp: string | null
  pulse: number | null
  temp: number | null
  glucose: number | null
  lastVisit: string      // date, format "YYYY-MM-DD"
}

// Shape of data needed to CREATE a patient (id is auto-generated, so we omit it)
export type NewPatient = Omit<Patient, "id">

// ── GET all patients ─────────────────────────────────────────────────────
export async function getPatients(): Promise<Patient[]> {
  const { data, error } = await supabase
    .from("patients")
    .select("*")
    .order("lastVisit", { ascending: false }) // most recent visit first

  if (error) {
    console.error("getPatients error:", error.message)
    throw new Error(error.message)
  }
  return data as Patient[]
}

// ── GET single patient by id ─────────────────────────────────────────────
export async function getPatientById(id: string): Promise<Patient> {
  const { data, error } = await supabase
    .from("patients")
    .select("*")
    .eq("id", id)
    .single()

  if (error) {
    console.error("getPatientById error:", error.message)
    throw new Error(error.message)
  }
  return data as Patient
}

// ── CREATE a new patient ──────────────────────────────────────────────────
export async function addPatient(patient: NewPatient): Promise<Patient> {
  const { data, error } = await supabase
    .from("patients")
    .insert([patient])
    .select()   // return the inserted row back
    .single()

  if (error) {
    console.error("addPatient error:", error.message)
    throw new Error(error.message)
  }
  return data as Patient
}